export const DATA ={
   firstname:'David',
   lastname:'Avdalyan',
   adress:'4605 Renwick Drive',
   city:'Philadelphia',
   state:'Pennsylvania',
   zipcode:'19108',
   number:'484-334-3585',
   ssn:'176-27-XXXX',
   username:'Davvva',
   password:'soRRRtin1998',
   confirm:'soRRRtin1998',
}
   export const data ={
      firstname:'Davид',
      lastname:'Avdal..yan',
      adress:'4605 Wick Drive',
      city:'Philadelphia',
      state:'Pennsylvania',
      zipcode:'12',
      number:'484-334-3585',
      ssn:'176-27-XXXX',
      username:'Davvva',
      password:'soRRRtin1998',
      confirm:'soRRRtin1998',
   }
   export const EXAMPLE = {
      Password:'soRRRtin1998',
      firstname:'David',
      lastname:'Avdalyan',
      adress:'4605 Wick Drive, 1680, Cypress',
      company:'Cypress',
      city:'Newtown Square',
      zipcode:'19073',
   }  
